"""empty message

Revision ID: 17bb036864dc
Revises: 9333772d1ea6
Create Date: 2023-08-11 17:43:39.102052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17bb036864dc'
down_revision = '9333772d1ea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.Integer(), nullable=True))
        batch_op.drop_column('votes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('votes', sa.INTEGER(), nullable=True))
        batch_op.drop_column('count')

    # ### end Alembic commands ###
