"""empty message

Revision ID: 250b4151cfcb
Revises: 51c1fc53590f
Create Date: 2023-08-08 15:00:10.814152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250b4151cfcb'
down_revision = '51c1fc53590f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('listing')

    # ### end Alembic commands ###
