"""empty message

Revision ID: 51c1fc53590f
Revises: 2c73e54396da
Create Date: 2023-08-08 09:22:52.708283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c1fc53590f'
down_revision = '2c73e54396da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('roomID', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('charges', sa.Float(), nullable=True),
    sa.Column('balanceBefore', sa.Float(), nullable=True),
    sa.Column('balanceAfter', sa.Float(), nullable=True),
    sa.Column('pending', sa.Boolean(), nullable=True),
    sa.Column('requested', sa.Boolean(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('account', sa.Float(), nullable=True),
    sa.Column('network', sa.String(), nullable=True),
    sa.Column('ref', sa.String(), nullable=True),
    sa.Column('prestoTransactionId', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
