"""empty message

Revision ID: d91fa9e0bfe2
Revises: 
Create Date: 2023-08-06 17:29:03.617280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91fa9e0bfe2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('locationTag', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('chatId', sa.String(), nullable=True),
    sa.Column('telegramBot', sa.String(), nullable=True),
    sa.Column('balance', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('callbackUrl', sa.String(), nullable=True),
    sa.Column('availablebalance', sa.Float(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dailyDisbursal', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('listingId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listingId'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('listingId', sa.Integer(), nullable=True),
    sa.Column('superListing', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listingId'], ['listing.id'], ),
    sa.ForeignKeyConstraint(['superListing'], ['listing.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suggestion', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('listingId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listingId'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggestions')
    op.drop_table('sub_listing')
    op.drop_table('image')
    op.drop_table('users')
    op.drop_table('listing')
    # ### end Alembic commands ###
