"""empty message

Revision ID: f29252677d1a
Revises: 43eeaf8246f0
Create Date: 2023-08-06 17:54:25.665447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29252677d1a'
down_revision = '43eeaf8246f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hostel', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('roomNumber', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('roomNumber')
        batch_op.drop_column('hostel')

    # ### end Alembic commands ###
